### ISSUE TITLE
Support Morphology Annotation?

### ISSUE THREAD

**Issue by GeorgeS2019** [notesjor/CorpusExplorer.Terminal.Console#2]
https://universaldependencies.org/format.html#morphological-annotation

**Comment by notesjor** [comment]
Hi @GeorgeS2019, the CorpusExplorer works agnostically, i.e. it doesn't matter what kind of layer you process with it.  The question is therefore rather where or how the corpus data comes into the CorpusExplorer. This 'import' then determines how and which data is stored in layers. Can you briefly describe this to me, or provide 3-5 example files for the input?

**Comment by GeorgeS2019** [comment]
@notesjor 

To be honest, there are not many **German** syntactic and semantic frameworks for .NET. 

The promising one [.NET] that integrates Spacy is e.g. [catalyst](https://github.com/curiosity-ai/catalyst/issues/105)

However, that requires embedding Python to run Spacy Python, passing the python spacy data output to .NET (limited Spacy wrapper).

1. It is unclear to me right now, if this CorpusExplorer framework could work independently of Python.

2. It is unclear if CorpusExplorer could provide Spacy **dependency** and **morphology** analysis.

Last, there is simply no **dependency tree viewer** for .NET, preferably either drawn using skiasharp or in blazor

**Comment by notesjor** [comment]
Basically, I would say that GitHub issues are not the right place to discuss such things. If you want to discuss this in detail or need help with something, you can find my contact details here:
https://notes.jan-oliver-ruediger.de/kontakt/

Anyway, briefly on your points - before I close this issue here:

- You are right, there are not many .NET libraries that deal with NLProc, especially German-NLProc. Catalyst is a fairly new and interesting framework that I have been following with interest for a quite some time. I've even considered integrating Catalyst - but haven't had the time yet. I'll add it to my todo list and get back to you when I have a testable prototype.
- The CorpusExplorer is written entirely in C#/.NET. However, I integrate a variety of other tools and programming languages, e.g. TreeTagger (only available as a binary - but one of the best taggers for the German language). Various Python but also Perl scripts (e.g. for calculating MTLD). CorpusExplorer installs these dependencies automatically. However, CorpusExplorer also works without these dependencies - just without these functions.
- The CorpusExplorer has been under development for over 10 years. Originally as my PhD project. This has now been completed - but I am still working on CorpusExplorer.
- Most users use the graphical user interface. You can find videos and instructions here:
https://notes.jan-oliver-ruediger.de/software/corpusexplorer-overview/ and e.g. https://www.youtube.com/watch?v=hVaN0eYEVNs. The GUI-installation automatically installs all dependencies. But there is also the possibility to use a console version. This means that all analyses can be controlled via the console. You can find documentation on this here: https://github.com/notesjor/CorpusExplorer.Terminal.Console
The console can also be used to integrate CorpusExplorer in Python, Jupyter Notebooks or any other programming language. Optionally, you can also turn a corpus into a web service and communicate with it via HTTP requests.
- I don't understand what you mean by the other applications (e.g. dependency tree viewer / skiasharp / blazor) - if this is a question, please ask me again by e-mail (see contact details).
